//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using static System.Collections.Specialized.BitVector32;
using System.Runtime;
using System.Xml.Linq;
using System;
using System.Configuration;


class Program
{
    
    }



namespace Project_Pluto.Properties
{
   
    
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
        internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
        {
            private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

            public static Settings Default
            {
                get
                {
                    return defaultInstance;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("DefaultUsername")]
            public string username
            {
                get
                {
                    return ((string)(this["username"]));
                }
                set
                {
                    this["username"] = value;
                }
            }
        }
    }


